# Generated by Django 4.2.3 on 2023-07-28 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assignment_course_task_assignment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 13, 3, 1, 331253)),
        ),
    ]
