# Generated by Django 4.2.4 on 2023-08-13 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_question_subject_question_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tasks',
            field=models.ManyToManyField(related_name='assignments', to='app.task'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 23, 11, 31, 620739)),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 23, 11, 31, 620739)),
        ),
    ]
