# Generated by Django 4.2.2 on 2023-08-14 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assignment_tasks_alter_assignment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 11, 5, 5, 874298)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 11, 5, 5, 876836)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
