# Generated by Django 4.2.2 on 2023-08-14 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_assignment_due_date_alter_reminder_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 11, 18, 40, 422696)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 11, 18, 40, 423695)),
        ),
    ]
