# Generated by Django 4.2.3 on 2023-08-15 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_assignment_due_date_alter_assignment_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 19, 39, 43, 963471)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='progress',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignments', to='app.task'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 19, 39, 43, 966002)),
        ),
    ]
